const  String  appLogo= "assets/excel_karror/excelKaroor.png";
const String  officialLogo ="assets/excel_karror/excel_karoor_logo.png";
const String nameOfInstitution = "EXCEL KAROOR";
const String nameInSmall = "Karoor";
const String nameInCapital = "EXCEL KAROOR";
const String companyName ="EXCEL";
const String companyNameSmall = "Excel";
const String chat ='ExcelKaroor Chat';
const String live ='ExcelKaroor Live';
